new branch commit
ossia/score-addon-spat pull request #4
Opened 2022-05-25 09:08 UTC by theurtel

2022-05-25 10:05 UTC, jcelerier requested changes

2022-05-25 10:05 UTC, jcelerier commented on Spat/AmbisonicMethods.cpp
> +    int dir, j, n, m, idx_Y;
or even better, initialize them when they come up (like this wwith all the variables on top is old C style)

2022-05-25 10:05 UTC, jcelerier commented on Spat/AmbisonicMethods.cpp
> +    float azimuth = azi*M_PI/180.0f;
constexpr float deg_to_rad = M_PI / 180.f;
const float azimuth = azi * deg_to_rad;

2022-05-25 10:05 UTC, jcelerier commented on Spat/AmbisonicMethods.cpp
> +            //std::cout<<i<<" "<<doneChannels<<std::endl;
this can go

2022-05-25 10:05 UTC, jcelerier commented on Spat/MonoToAmbiModel.hpp
> +        //halp::dynamic_audio_bus<"Output", float> audio;
this can go

2022-05-25 10:05 UTC, jcelerier commented on Spat/Test.hpp
> +      //fonctionne jusqu'à i<4, crashe à partir de i<5
is it still the case ?

2022-05-25 14:28 UTC, theurtel commented on Spat/AmbisonicMethods.cpp
>  using namespace std;
Ici j'ai recopié la permission notice parce que la plupart des méthodes de la classe sont tirées de sa lib (voire quasi copiées/collées pour certaines)
Je l'enlève ?

2022-05-25 17:44 UTC, jcelerier commented on Spat/AmbisonicMethods.cpp
>  using namespace std;
Ah non mon commentaire était par rapport au using namespace std ; aha.

On peut laisser la notice sans souci, et on le mettra dans le readme aussi

2022-06-14 15:18 UTC, jcelerier commented
> @theurtel [salu j'essaie de fix mon git :)))](https://github.com/ossia/score-addon-spat/pull/4/commits/88dce3dab59bc1be1635e470176c27fab647a10a)

hehe

2022-06-15 09:50 UTC, merged